name: BalancedDiet
version: '1.0.0'
main: me.vaan.balanceddiet.BalancedDiet
api-version: '1.20'

permissions:

  balanceddiet.command.profile:
    description: Gives info about the player diet
    default: true

  balanceddiet.command.effects:
    description: Gives info about the positive/negative effects of follow a good/bad diet
    default: true

  balanceddiet.command.save:
    description: Saves to the database async
    default: op

  balanceddiet.command.profile.other:
    description: Gives info about another player diet
    default: op

  balanceddiet.command.clear:
    description: Clears your or another player diet
    default: op